name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: andrelucas21
        password: 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
    - name: Build the Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag ghcr.io/andrelucas21/image-teste:latest
        docker push ghcr.io/andrelucas21/image-teste:latest
