name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag ghcr.io/andrelucas21/image-teste:latest
    
    - name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      run: echo "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" | docker login ghcr.io -u $ --password-stdin
        
    - name: Push image
      run: docker push ghcr.io/andrelucas21/image-teste:latest
