name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag ghcr.io/andrelucas21/image-teste:latest
        docker run ghcr.io/andrelucas21/image-teste:latest
        docker push ghcr.io/andrelucas21/image-teste:latest
